export const ROUTES_IMAGE = {
  logo: '/assets/imagenes/full_logo.png',
  logo_header: '/assets/imagenes/logo_transparente.png',
  sar_alistamiento: '/assets/imagenes/sar-alistamiento.png',
  sar_aprovisionamiento: '/assets/imagenes/sar-aprovisionamiento.png',
  sar_aseguramiento: '/assets/imagenes/sar-aseguramiento.png',
  sar_bodegas: '/assets/imagenes/sar-bodegas.png',
  sar_budget: '/assets/imagenes/sar-budget.png',
  sar_cam: '/assets/imagenes/sar-cam.png',
  sar_configuracion: '/assets/imagenes/sar-configuracion.png',
  sar_cube: '/assets/imagenes/sar-cube.png',
  sar_element: '/assets/imagenes/sar-element.png',
  sar_element_0: '/assets/imagenes/sar-element-0.png',
  sar_eye: '/assets/imagenes/sar-eye.png',
  sar_eye_0: '/assets/imagenes/sar-eye-0.png',
  sar_gear: '/assets/imagenes/sar-gear.png',
  sar_historicos: '/assets/imagenes/sar-historicos.png',
  sar_info: '/assets/imagenes/sar-info.png',
  sar_report: '/assets/imagenes/sar-report.png',
  sar_report_0: '/assets/imagenes/sar-report-0.png',
  sar_reportes: '/assets/imagenes/sar-reportes.png',
  sar_time: '/assets/imagenes/sar-time.png',
};
