// RUTAS DE LA NAVEGACION
import {MODULO} from './navigation.string.const';

export const INTERNAL_PATHS = {
  LOGIN: `${MODULO.LOGIN.link}`,

  RAIZ: `${MODULO.RAIZ.link}`,


  APROVISIONAMIENTO: `${MODULO.APROVISIONAMIENTO.link}`,

  APROVISIONAMIENTO__PRESUPUESTOS: `${MODULO.APROVISIONAMIENTO.PRESUPUESTOS.link}`,
  APROVISIONAMIENTO__PRESUPUESTOS__CREACION_DOCUMENTOS: `${MODULO.APROVISIONAMIENTO.PRESUPUESTOS.CREACION_DOCUMENTOS.link}`,
  APROVISIONAMIENTO__PRESUPUESTOS__CONSULTA_DOCUMENTOS: `${MODULO.APROVISIONAMIENTO.PRESUPUESTOS.CONSULTA_DOCUMENTOS.link}`,
  APROVISIONAMIENTO__PRESUPUESTOS__CONSULTA_FACTIBILIDADES: `${MODULO.APROVISIONAMIENTO.PRESUPUESTOS.CONSULTA_FACTIBILIDADES.link}`,
  APROVISIONAMIENTO__PRESUPUESTOS__INFORME_DOCUMENTOS: `${MODULO.APROVISIONAMIENTO.PRESUPUESTOS.INFORME_DOCUMENTOS.link}`,

  APROVISIONAMIENTO__SOLICITUDES: `${MODULO.APROVISIONAMIENTO.SOLICITUDES.link}`,
  APROVISIONAMIENTO__DOCUMENTOS_DE_LIQUIDACION: `${MODULO.APROVISIONAMIENTO.DOCUMENTOS_DE_LIQUIDACION.link}`,
  APROVISIONAMIENTO__EQUIPOS: `${MODULO.APROVISIONAMIENTO.EQUIPOS.link}`,
  APROVISIONAMIENTO__ENLACES: `${MODULO.APROVISIONAMIENTO.ENLACES.link}`,
  APROVISIONAMIENTO__REGISTRAR_FACTURA_DE_LIQUIDACIONES: `${MODULO.APROVISIONAMIENTO.REGISTRAR_FACTURA_DE_LIQUIDACIONES.link}`,



  ASEGURAMIENTO: `${MODULO.ASEGURAMIENTO.link}`,

  ASEGURAMIENTO__SOLICITUDES_PREVENTIVAS: `${MODULO.ASEGURAMIENTO.link}`,
  ASEGURAMIENTO__SOLICITUDES_DE_EMERGENCIA: `${MODULO.ASEGURAMIENTO.link}`,
  ASEGURAMIENTO__ACTA_DE_REPORTE_DE_FALLA: `${MODULO.ASEGURAMIENTO.link}`,
  ASEGURAMIENTO__DOCUMENTOS_DE_LIQUIDACION: `${MODULO.ASEGURAMIENTO.link}`,


  ALISTAMIENTO: `${MODULO.ALISTAMIENTO.link}`,
  ALISTAMIENTO__PRESUPUESTOS: `${MODULO.ASEGURAMIENTO.link}`,
  ALISTAMIENTO__SOLICITUDES: `${MODULO.ASEGURAMIENTO.link}`,
  ALISTAMIENTO__DOCUMENTOS_DE_LIQUIDACION: `${MODULO.ASEGURAMIENTO.link}`,
  ALISTAMIENTO__ADMINISTRACION_DE_TRONCALES: `${MODULO.ASEGURAMIENTO.link}`,

};
